### ISSUE TITLE
Develop cell type-specific signatures. For example, I want to deconvolute NK cells, so I want sufficient markers (and not more) to achieve separation from NK cells to the others.

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#17]
I want to select 
epithelial, immune cells
t cell bcell nkcell
activated nk resting nk

**Comment by stemangiola** [comment]
A visual example of tree subselection


![image](https://user-images.githubusercontent.com/7232890/129135132-22189bc4-0f86-4d2a-990e-3dc652a9a62c.png)


Packages to select ancestors and their brothers, `tidytree` `tidygraph`

https://yulab-smu.top/treedata-book/chapter2.html

**Comment by jianwu1** [comment]
Find the siblings of the node and ancestors and siblings of the ancestors

**Comment by jianwu1** [comment]
@stemangiola 
Hi Stefano,

The tree_subset function is completed. It doesn't have branch.length information but this does not affect plotting the tree.
![image](https://user-images.githubusercontent.com/62498686/131788639-4f7dacc1-1a85-47df-b595-4fa8c9692eea.png)
![image](https://user-images.githubusercontent.com/62498686/131788723-15e70d23-834b-46a6-bdca-e66514186b29.png)
![image](https://user-images.githubusercontent.com/62498686/131788776-951a0189-fb42-4a62-9d27-432df76b1c68.png)
![image](https://user-images.githubusercontent.com/62498686/131789145-5f8051d6-c18e-4bdb-b7fb-ff3764afb8dd.png)
![image](https://user-images.githubusercontent.com/62498686/131788975-f2c1fbf0-8c41-4154-9e4b-c98279d212b4.png)

Input full tree:
![image](https://user-images.githubusercontent.com/62498686/131789305-b2f7bffa-8cb8-45be-af98-c59b08741ee2.png)

**Comment by stemangiola** [comment]
Well done. In this way you don't have to touch any other piece of your pipeline for this implementation. 

I guess you can 

1) pick just one method that performs well
2) compare full tree vs subtree (for cell type X, maybe one of the ones that perform badly for deconvolution)
3) calculate deconvolution error for cell type X

We expect that the error would decrease for cell type X while increasing for all the others.

**Comment by jianwu1** [comment]
try to resolve t_helper_h1, t_CD4_memory_central, t_CD8_memory_effector with:
hierarchical_pairwise_contrast_bayes___naive_penalty &
non_hierarchical_mean_contrast_edgR_PValue_silhouette_penalty

**Comment by jianwu1** [comment]
@stemangiola 

Hi Stefano,

Do you have time for a quick meeting? This result is a bit contrary to our expectation.
The **blue** uses signatures from hierarchical_mean_contrast_bayes_curvature stream and the **t_helper_subtree** for deconvolution 100 times;
The **green** uses signatures from the same stream and the **full tree** for 100 deconvolution
The red uses signature from cibersortx for 100 deconvolution.

The subtree used is:
![image](https://user-images.githubusercontent.com/62498686/134460905-75492d41-3885-4460-b826-dd5b643cccf8.png)

The signature selected was rich for markers for t_helper cells:
![image](https://user-images.githubusercontent.com/62498686/134461451-5ef4295a-a4e7-4fef-b859-465f05a4d87b.png)
![image](https://user-images.githubusercontent.com/62498686/134461666-d1e35b2c-094c-4f60-abd8-ba73fda6d5c6.png)


However, the absolute deconvolution error doesn't necessarily seem to be reduced by the signature rich in t_helper markers.
The numbers at the end of each cell type is the number of samples for that cell type in the data.
steams are ordered by descending median of absolute deconvolution error.

![image](https://user-images.githubusercontent.com/62498686/134462438-6a987efe-63bc-432c-9863-706c5d72b2b3.png)

**Comment by jianwu1** [comment]
![image](https://user-images.githubusercontent.com/62498686/134905287-04863423-c6a6-45b5-bd3e-4d15df6aec1c.png)


![image](https://user-images.githubusercontent.com/62498686/134904521-8cf43c57-8f08-4221-bfb3-c5deea609863.png)

![image](https://user-images.githubusercontent.com/62498686/134904907-563a8962-ddf1-4a3a-8287-00d531a50875.png)

![image](https://user-images.githubusercontent.com/62498686/134904361-ff6a6389-45f6-4793-8a94-1eaf79183e40.png)

**Comment by stemangiola** [comment]
Thanks Jian, are you selecting the markers that are in the top half of highly transcribed for the selected cell type? If a marker is lowly transcribed (even if different) we don't care much.

**Comment by jianwu1** [comment]
output using the corrected cibersortx signature: before cibersortx signature were generated from the contrasts between 37 cell types which doesnt make sense in cases of t_cell - t_CD4 or t_cell - (t_CD4 + t_helper + ...)/36. Now the signatures generated from cibersortx are only between 27 leaf cell types of the tree. 
However results are pretty much the same.

I have an explanation: 
Now I don't think silhouette selection is necessarily better than naive selection from the benchmark plot. 
![boxplot_deconvolution_by_method_dim2](https://user-images.githubusercontent.com/62498686/136249263-e9376be7-a76f-415e-978e-08fcb41f695f.png)

I think they have different focuses: 
Naive selection selects the best signature for leaf nodes because it selects the most enriched genes in children nodes while silhouette selection selects the best signature for internal nodes as only genes from contrasts that best separate all siblings are selected. In my current tree, the cell types I'm trying to compare are all leaf nodes: t_helper_h1, t_helper_h2, t_helper_h17.
I'll try the signature I got from a high ranking naive method and reproduce the same plots.

![image](https://user-images.githubusercontent.com/62498686/136245654-8c7436ba-3c5e-4c62-817e-603435b1fbf0.png)

![image](https://user-images.githubusercontent.com/62498686/136245572-e971bb8d-5c6e-49ba-b846-9340c352636d.png)

expression level of signature in t_helper_h1, t_helper_h2, t_helper_h17:
![image](https://user-images.githubusercontent.com/62498686/136247333-77c7c829-65ef-4eb9-8403-62cb639dfdd4.png)

![image](https://user-images.githubusercontent.com/62498686/136248532-4d4f0007-079a-4061-8249-49cd9b662490.png)

![image](https://user-images.githubusercontent.com/62498686/136248677-69426752-a424-40fe-b554-cd4dbaf90cca.png)

**Comment by jianwu1** [comment]
using naive signature selection:
![image](https://user-images.githubusercontent.com/62498686/136303226-b68aa878-30b5-4c83-bc42-ebac3045fe6d.png)

![image](https://user-images.githubusercontent.com/62498686/136302765-ccd2c3d0-5343-40b2-8d16-b80e501b9e2b.png)

![image](https://user-images.githubusercontent.com/62498686/136304755-12e1ee36-8e04-4e54-aae7-0f78c3ba4c48.png)

![image](https://user-images.githubusercontent.com/62498686/136304805-77822725-199c-41a1-b2e4-f4f474c293d4.png)

![image](https://user-images.githubusercontent.com/62498686/136304876-3426e57c-7f7b-4d87-8c78-5577b668bea8.png)

**Comment by jianwu1** [comment]
using naive method dim=4:
![image](https://user-images.githubusercontent.com/62498686/137807110-4df82974-b55c-46f7-82e6-7e7065c4e46e.png)
![image](https://user-images.githubusercontent.com/62498686/137807004-cc7be066-9e6e-49d9-ad2b-c6a08c3e0d0b.png)

**Comment by Kamran-Khan96** [comment]
Obsolete
