### ISSUE TITLE
polish cellsigDB (the minimum standard)

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/cellsig#49]
todos:

- Execute as sanity check this file https://github.com/stemangiola/cellsig/blob/Kamran/dev/process_counts.R and make sure you can reconstruct the raw caounts
- If you did add more raw data, create a new R script called `parse_fourth_databse.R`
- Add the call to `parse_fourth_databse.R` to `process_counts.R` and re execute process counts to see that you get the raw data back
- polish any of the `parse_*_databse.R` when you find mistakes (JUST THE BIG ONES)

**Comment by Kamran-Khan96** [comment]
Hi @stemangiola ,


Apologies for the late response.


It seems in the the source files of the raw counts aren't in the git repository yet. Particularly, the source file for calling the functions in aren't even specified in `parse_second_database.R` and `parse_third_database.R`.  Maybe I'm understanding it wrong.

I'll just try to pinpoint the major issues (if there's any) rather than going very deep into the matter.

**Comment by stemangiola** [comment]
> It seems in the the source files of the raw counts aren't in the git repository yet. 

When you are in the WEHI server I will share the database directory with you.

> Particularly, the source file for calling the functions in aren't even specified in `parse_second_database.R` and `parse_third_database.R`. Maybe I'm understanding it wrong.

I'm trying to understand this. I have asked access to Jian directory at WEHI, I will try to find those files there

**Comment by Kamran-Khan96** [comment]
Resolved
